const COMPANIES = [
  {
    name: "Google",
    slug: "google",
    aliases: ["google", "google india", "google llc"],
    industry: "Technology",
    headquarters: "Mountain View, CA",
    foundedYear: 1998,
    headcountRange: "100000+",
  },
  {
    name: "Amazon",
    slug: "amazon",
    aliases: ["amazon", "amazon web services", "aws"],
    industry: "E-commerce and Cloud",
    headquarters: "Seattle, WA",
    foundedYear: 1994,
    headcountRange: "100000+",
  },
  {
    name: "TCS",
    slug: "tcs",
    aliases: ["tcs", "tata consultancy services", "tata consultancy"],
    industry: "IT Services",
    headquarters: "Mumbai, India",
    foundedYear: 1968,
    headcountRange: "100000+",
  },
  {
    name: "Microsoft",
    slug: "microsoft",
    aliases: ["microsoft", "microsoft india"],
    industry: "Technology",
    headquarters: "Redmond, WA",
    foundedYear: 1975,
    headcountRange: "100000+",
  },
  {
    name: "Meta",
    slug: "meta",
    aliases: ["meta", "meta platforms"],
    industry: "Social Technology",
    headquarters: "Menlo Park, CA",
    foundedYear: 2004,
    headcountRange: "50000-100000",
  },
  {
    name: "United Health Group",
    slug: "united-health-group",
    aliases: ["united health group", "unitedhealth group", "uhg"],
    industry: "Healthcare",
    headquarters: "Minnetonka, MN",
    foundedYear: 1977,
    headcountRange: "100000+",
  },
  {
    name: "Flipkart",
    slug: "flipkart",
    aliases: ["flipkart", "flipkart india"],
    industry: "E-commerce",
    headquarters: "Bengaluru, India",
    foundedYear: 2007,
    headcountRange: "10000-50000",
  },
  {
    name: "Meesho",
    slug: "meesho",
    aliases: ["meesho"],
    industry: "E-commerce",
    headquarters: "Bengaluru, India",
    foundedYear: 2015,
    headcountRange: "1000-5000",
  },
  {
    name: "NVIDIA",
    slug: "nvidia",
    aliases: ["nvidia", "nvidia corporation"],
    industry: "Semiconductors",
    headquarters: "Santa Clara, CA",
    foundedYear: 1993,
    headcountRange: "10000-50000",
  },
  {
    name: "Infosys",
    slug: "infosys",
    aliases: ["infosys", "infosys limited"],
    industry: "IT Services",
    headquarters: "Bengaluru, India",
    foundedYear: 1981,
    headcountRange: "100000+",
  },
  {
    name: "Wipro",
    slug: "wipro",
    aliases: ["wipro", "wipro limited"],
    industry: "IT Services",
    headquarters: "Bengaluru, India",
    foundedYear: 1945,
    headcountRange: "100000+",
  },
  {
    name: "Razorpay",
    slug: "razorpay",
    aliases: ["razorpay", "razorpay software"],
    industry: "Fintech",
    headquarters: "Bengaluru, India",
    foundedYear: 2014,
    headcountRange: "1000-5000",
  },
  {
    name: "Zepto",
    slug: "zepto",
    aliases: ["zepto"],
    industry: "Quick Commerce",
    headquarters: "Mumbai, India",
    foundedYear: 2021,
    headcountRange: "1000-5000",
  },
];

const LEGAL_SUFFIXES = new Set([
  "private",
  "pvt",
  "limited",
  "ltd",
  "inc",
  "llc",
  "corp",
  "corporation",
  "company",
  "co",
]);

export { COMPANIES, LEGAL_SUFFIXES };
